# -*- coding: utf-8 -*-
"""Arquivos_e_funcoes.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IxKY56hGc4uhnpf4qxv9dSpytbm_11aS

**Tópicos trabalhados:**


*   Leitura;
*   Escritra;
*   Funções;
*   Escopo.

**0. Preparação do ambiente**

**carros.csv: arquivo csv com informações sobre carros (venda, manutenção, portas, etc.).**
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile carros.csv
# id,valor_venda,valor_manutencao,portas,pessoas,porta_malas
# 1,vhigh,med,2,2,small
# 2,med,vhigh,2,2,small
# 3,low,vhigh,2,2,small
# 4,low,high,2,2,small
# 5,low,high,2,2,small
# 6,low,high,4,4,big
# 7,low,high,4,4,big
# 8,low,med,2,2,small
# 9,low,med,2,2,small
# 10,low,med,2,2,small
# 11,low,med,4,4,big
# 12,low,low,2,2,small
# 13,low,low,4,4,small
# 14,low,low,4,4,med

"""**musica.txt: arquivo texto com a letra da música Roda Viva do Chico Buarque.**"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile musica.txt
# Roda Viva
# Chico Buarque
# Tem dias que a gente se sente
# Como quem partiu ou morreu
# A gente estancou de repente
# Ou foi o mundo então que cresceu
# A gente quer ter voz ativa
# No nosso destino mandar
# Mas eis que chega a roda viva
# E carrega o destino pra lá
# Roda mundo, roda-gigante
# Roda moinho, roda pião
# O tempo rodou num instante
# Nas voltas do meu coração
# A gente vai contra a corrente
# Até não poder resistir
# Na volta do barco é que sente
# O quanto deixou de cumprir
# Faz tempo que a gente cultiva
# A mais linda roseira que há
# Mas eis que chega a roda viva
# E carrega a roseira pra lá
# Roda mundo, roda-gigante
# Roda moinho, roda pião

"""**1.0 Criando a função que extrai uma coluna do arquivo csv e transforma em uma lista**"""

def extrai_coluna_csv(nome_arquivo: str, indice_coluna: int, tipo_dado: str):

 coluna = []
 with open(file=nome_arquivo,mode='r',encoding='utf8') as arquivo:
   arquivo.readline()
   linha = arquivo.readline()
   while linha:
     l = linha.split(',')
     valor = l[indice_coluna]
     if tipo_dado == 'str':
       coluna.append(str(valor))
     elif tipo_dado == 'int':
       coluna.append(int(valor))
     linha = arquivo.readline()
        
   return coluna

#Testando com a coluna "valor_venda"
valor_venda = extrai_coluna_csv(
 nome_arquivo = './carros.csv',
 indice_coluna = 1,
 tipo_dado = 'str'
)
print(valor_venda)

#Testando com a coluna "pessoas"
pessoas = extrai_coluna_csv(
    nome_arquivo = './carros.csv',
    indice_coluna = 4,
    tipo_dado = 'str',
)
print(pessoas)

"""**2.0 Criando a função que extrai as palavras de uma linha do arquivo txt e transforma em uma lista**"""

def extrai_linha_txt(nome_arquivo: str, numero_linha: int):
  
 palavras_linha = []
 with open(file=nome_arquivo,mode='r',encoding='utf8') as arquivo:
   numero_linha_atual = 1
   linha = arquivo.readline()
   while numero_linha_atual < numero_linha:
     linha = arquivo.readline()
     numero_linha_atual += 1
   palavras_linha = linha.split(' ')
   return palavras_linha

#Testando com a extração da Linha 10
linha10 = extrai_linha_txt(
    nome_arquivo = './musica.txt',
    numero_linha = 9
)
print(linha10)